// This was generated by cms app (yarn generate:types)

export interface Page {
  id: string;
  title: string;
  content?: {
    [k: string]: unknown;
  }[];
  site: Site;
  _status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}

export interface Site {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface News {
  id: string;
  title: string;
  coverImage: File;
  content?: {
    [k: string]: unknown;
  }[];
  author: User;
  newsCategory: NewsCategory;
  site: Site;
  slug: string;
  _status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}

export interface File {
  id: string;
  alt: string;
  site: Site;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  roles?: ("admin" | "editor" | "subEditor")[];
  sites?: Site[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}

export interface NewsCategory {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  title: string;
  logo: File;
  projectType: ProjectCategory;
  location: string;
  size: string;
  coverImage: File;
  overview: {
    [k: string]: unknown;
  }[];
  locationTab: {
    [k: string]: unknown;
  }[];
  mapImage: File;
  site: Site;
  _status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}

export interface ProjectCategory {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface Career {
  id: string;
  title: string;
  location: string;
  responsibilities: {
    [k: string]: unknown;
  }[];
  careersCategory: CareerCategory;
  site: Site;
  _status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}

export interface CareerCategory {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface Advertisement {
  id: string;
  title: string;
  content?: {
    [k: string]: unknown;
  }[];
  site: Site;
  createdAt: string;
  updatedAt: string;
}

export interface Menu {
  id: string;
  owner?: User;
  createdAt: string;
  updatedAt: string;
}
